apiVersion: v1
kind: PersistentVolume
metadata:
  name: datavolume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  hostPath:
    path: "/data/storage"
    type: Directory
  claimRef:
    name: datavolume-claim